//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CT.GeneralObjectResource
{
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EnumResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EnumResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TAS.Resources.EnumResources", typeof(EnumResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Head of Equity.
        /// </summary>
        public static string AdminType_HeadOfEquity {
            get {
                return ResourceManager.GetString("AdminType_HeadOfEquity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Head of Offshore.
        /// </summary>
        public static string AdminType_HeadOfOffShore {
            get {
                return ResourceManager.GetString("AdminType_HeadOfOffShore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT Admin.
        /// </summary>
        public static string AdminType_ITAdmin {
            get {
                return ResourceManager.GetString("AdminType_ITAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compliance Manager.
        /// </summary>
        public static string ApproverType_ComplianceManager {
            get {
                return ResourceManager.GetString("ApproverType_ComplianceManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compliance Officer.
        /// </summary>
        public static string ApproverType_ComplianceOfficer {
            get {
                return ResourceManager.GetString("ApproverType_ComplianceOfficer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy.
        /// </summary>
        public static string DetailTransactionType_Buy {
            get {
                return ResourceManager.GetString("DetailTransactionType_Buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sell.
        /// </summary>
        public static string DetailTransactionType_Sell {
            get {
                return ResourceManager.GetString("DetailTransactionType_Sell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string Gender_Female {
            get {
                return ResourceManager.GetString("Gender_Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string Gender_Male {
            get {
                return ResourceManager.GetString("Gender_Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Gender_Other {
            get {
                return ResourceManager.GetString("Gender_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.
        /// </summary>
        public static string PageSize_10 {
            get {
                return ResourceManager.GetString("PageSize_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20.
        /// </summary>
        public static string PageSize_20 {
            get {
                return ResourceManager.GetString("PageSize_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        public static string PageSize_5 {
            get {
                return ResourceManager.GetString("PageSize_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50.
        /// </summary>
        public static string PageSize_50 {
            get {
                return ResourceManager.GetString("PageSize_50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent RequestId.
        /// </summary>
        public static string ParentRequestId {
            get {
                return ResourceManager.GetString("ParentRequestId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        public static string ProcessingStatus_Failed {
            get {
                return ResourceManager.GetString("ProcessingStatus_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In progress.
        /// </summary>
        public static string ProcessingStatus_InProgress {
            get {
                return ResourceManager.GetString("ProcessingStatus_InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string ProcessingStatus_Pending {
            get {
                return ResourceManager.GetString("ProcessingStatus_Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string ProcessingStatus_Processed {
            get {
                return ResourceManager.GetString("ProcessingStatus_Processed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.
        /// </summary>
        public static string RemiderStartTimeInHours_Eight {
            get {
                return ResourceManager.GetString("RemiderStartTimeInHours_Eight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 18.
        /// </summary>
        public static string RemiderStartTimeInHours_Eighteen {
            get {
                return ResourceManager.GetString("RemiderStartTimeInHours_Eighteen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11.
        /// </summary>
        public static string RemiderStartTimeInHours_Eleven {
            get {
                return ResourceManager.GetString("RemiderStartTimeInHours_Eleven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15.
        /// </summary>
        public static string RemiderStartTimeInHours_Fifteen {
            get {
                return ResourceManager.GetString("RemiderStartTimeInHours_Fifteen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        public static string RemiderStartTimeInHours_Five {
            get {
                return ResourceManager.GetString("RemiderStartTimeInHours_Five", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        public static string RemiderStartTimeInHours_Four {
            get {
                return ResourceManager.GetString("RemiderStartTimeInHours_Four", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14.
        /// </summary>
        public static string RemiderStartTimeInHours_Fourteen {
            get {
                return ResourceManager.GetString("RemiderStartTimeInHours_Fourteen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9.
        /// </summary>
        public static string RemiderStartTimeInHours_Nine {
            get {
                return ResourceManager.GetString("RemiderStartTimeInHours_Nine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 19.
        /// </summary>
        public static string RemiderStartTimeInHours_Nineteen {
            get {
                return ResourceManager.GetString("RemiderStartTimeInHours_Nineteen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        public static string RemiderStartTimeInHours_One {
            get {
                return ResourceManager.GetString("RemiderStartTimeInHours_One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7.
        /// </summary>
        public static string RemiderStartTimeInHours_Seven {
            get {
                return ResourceManager.GetString("RemiderStartTimeInHours_Seven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 17.
        /// </summary>
        public static string RemiderStartTimeInHours_Seventeen {
            get {
                return ResourceManager.GetString("RemiderStartTimeInHours_Seventeen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.
        /// </summary>
        public static string RemiderStartTimeInHours_Six {
            get {
                return ResourceManager.GetString("RemiderStartTimeInHours_Six", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16.
        /// </summary>
        public static string RemiderStartTimeInHours_Sixteen {
            get {
                return ResourceManager.GetString("RemiderStartTimeInHours_Sixteen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.
        /// </summary>
        public static string RemiderStartTimeInHours_Ten {
            get {
                return ResourceManager.GetString("RemiderStartTimeInHours_Ten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13.
        /// </summary>
        public static string RemiderStartTimeInHours_Thirteen {
            get {
                return ResourceManager.GetString("RemiderStartTimeInHours_Thirteen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        public static string RemiderStartTimeInHours_Three {
            get {
                return ResourceManager.GetString("RemiderStartTimeInHours_Three", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12.
        /// </summary>
        public static string RemiderStartTimeInHours_Twelve {
            get {
                return ResourceManager.GetString("RemiderStartTimeInHours_Twelve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20.
        /// </summary>
        public static string RemiderStartTimeInHours_Twenty {
            get {
                return ResourceManager.GetString("RemiderStartTimeInHours_Twenty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 25.
        /// </summary>
        public static string RemiderStartTimeInHours_Twentyfive {
            get {
                return ResourceManager.GetString("RemiderStartTimeInHours_Twentyfive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24.
        /// </summary>
        public static string RemiderStartTimeInHours_Twentyfour {
            get {
                return ResourceManager.GetString("RemiderStartTimeInHours_Twentyfour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 21.
        /// </summary>
        public static string RemiderStartTimeInHours_Twentyone {
            get {
                return ResourceManager.GetString("RemiderStartTimeInHours_Twentyone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 23.
        /// </summary>
        public static string RemiderStartTimeInHours_Twentythree {
            get {
                return ResourceManager.GetString("RemiderStartTimeInHours_Twentythree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 22.
        /// </summary>
        public static string RemiderStartTimeInHours_Twentytwo {
            get {
                return ResourceManager.GetString("RemiderStartTimeInHours_Twentytwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        public static string RemiderStartTimeInHours_Two {
            get {
                return ResourceManager.GetString("RemiderStartTimeInHours_Two", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to April.
        /// </summary>
        public static string ReportMonth_April {
            get {
                return ResourceManager.GetString("ReportMonth_April", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to August.
        /// </summary>
        public static string ReportMonth_August {
            get {
                return ResourceManager.GetString("ReportMonth_August", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to December.
        /// </summary>
        public static string ReportMonth_December {
            get {
                return ResourceManager.GetString("ReportMonth_December", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to February.
        /// </summary>
        public static string ReportMonth_February {
            get {
                return ResourceManager.GetString("ReportMonth_February", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to January.
        /// </summary>
        public static string ReportMonth_January {
            get {
                return ResourceManager.GetString("ReportMonth_January", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to July.
        /// </summary>
        public static string ReportMonth_July {
            get {
                return ResourceManager.GetString("ReportMonth_July", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to June.
        /// </summary>
        public static string ReportMonth_June {
            get {
                return ResourceManager.GetString("ReportMonth_June", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to March.
        /// </summary>
        public static string ReportMonth_March {
            get {
                return ResourceManager.GetString("ReportMonth_March", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to May.
        /// </summary>
        public static string ReportMonth_May {
            get {
                return ResourceManager.GetString("ReportMonth_May", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to November.
        /// </summary>
        public static string ReportMonth_November {
            get {
                return ResourceManager.GetString("ReportMonth_November", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to October.
        /// </summary>
        public static string ReportMonth_October {
            get {
                return ResourceManager.GetString("ReportMonth_October", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to September.
        /// </summary>
        public static string ReportMonth_September {
            get {
                return ResourceManager.GetString("ReportMonth_September", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        public static string RequestStatus_Approved {
            get {
                return ResourceManager.GetString("RequestStatus_Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string RequestStatus_Completed {
            get {
                return ResourceManager.GetString("RequestStatus_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overdue.
        /// </summary>
        public static string RequestStatus_Overdue {
            get {
                return ResourceManager.GetString("RequestStatus_Overdue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string RequestStatus_Pending {
            get {
                return ResourceManager.GetString("RequestStatus_Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending For Sell.
        /// </summary>
        public static string RequestStatus_PendingForSell {
            get {
                return ResourceManager.GetString("RequestStatus_PendingForSell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected.
        /// </summary>
        public static string RequestStatus_Rejected {
            get {
                return ResourceManager.GetString("RequestStatus_Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMI.
        /// </summary>
        public static string RequestStatus_SMI {
            get {
                return ResourceManager.GetString("RequestStatus_SMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Not Done.
        /// </summary>
        public static string RequestStatus_TransactionNotDone {
            get {
                return ResourceManager.GetString("RequestStatus_TransactionNotDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unresolved.
        /// </summary>
        public static string RequestStatus_Unresolved {
            get {
                return ResourceManager.GetString("RequestStatus_Unresolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Status_Active {
            get {
                return ResourceManager.GetString("Status_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string Status_All {
            get {
                return ResourceManager.GetString("Status_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Active.
        /// </summary>
        public static string Status_InActive {
            get {
                return ResourceManager.GetString("Status_InActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy.
        /// </summary>
        public static string TransactionType_Buy {
            get {
                return ResourceManager.GetString("TransactionType_Buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sell.
        /// </summary>
        public static string TransactionType_Sell {
            get {
                return ResourceManager.GetString("TransactionType_Sell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        public static string UploadStatus_Failed {
            get {
                return ResourceManager.GetString("UploadStatus_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In progress.
        /// </summary>
        public static string UploadStatus_InProgress {
            get {
                return ResourceManager.GetString("UploadStatus_InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string UploadStatus_Pending {
            get {
                return ResourceManager.GetString("UploadStatus_Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string UploadStatus_Processed {
            get {
                return ResourceManager.GetString("UploadStatus_Processed", resourceCulture);
            }
        }
    }
}
